#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Verify nginx is running
if pgrep nginx >/dev/null; then
     echo 'Nginx is running'
else
     # Restart nginx
     sudo service nginx restart
     # sudo kill -s HUP $(pgrep nginx)
fi

# Create index.html with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html
