#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.
#++    Redirects /redirect_me to another page with a 301 Moved Permanently response.

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (with sudo)"
    exit 1
fi

# Update package list
apt-get update
# Install nginx
apt-get install -y nginx

# Create index.html with "Hello World!"
echo 'Hello World!' | sudo tee /etc/nginx/html/index.html

# Configure Nginx to listen on port 80 and serve files from /etc/nginx/html
cat << EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    listen [::]:80;
    server_name 322021-web-01;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /etc/nginx/html;
        index index.html index.htm;
    }
}
EOF

# Enable the new site configuration
ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart
