#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.
#++    Redirects /redirect_me to another page with a 301 Moved Permanently response.

# Update package list
sudo apt-get update
# Install nginx
sudo apt-get install -y nginx

# Create index.html with "Hello World!"
echo '
    <html>
    <head></head>
    <body>
        <h1>Hello World!</h1>
    </body>
    </html>
    ' | sudo tee /etc/nginx/html/index.html

# Configure Nginx to listen on port 80 and serve files from /etc/nginx/html
cat << EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /redirect_me {
        return 301 https://youtube.com;
    }

    location / {
        root /etc/nginx/html;
        index index.html index.htm;
    }
}
EOF

# Enable the new site configuration
sudo ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
