#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo '
    <html>
    <head></head>
    <body>
        <h1>Hello! Welcome</h1>
        <h2>I am <strong>Ezechiel Kiregha</strong>,<br>
        Co-Founder and CEO at <strong>Kiregha Corporation.</strong></h2>
    </body>
    </html>
    ' | sudo tee /etc/nginx/html/index.html

# Performing a "moved permanently redirection" (301)
# new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ezechielkiregha permanent;"
# sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default


# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

cat << EOF > /etc/nginx/sites-available/custom_conf
server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /etc/nginx/html;

    location /redirect_me {
        return 301 https://youtube.com/@AI_Mirror_Company;
    }

    error_page 404 /404.html;

    location / {
        index index.html index.htm;
    }
}
EOF

# Delete/Desactivate the default page from enabled sites
sudo rm /etc/nginx/sites-enabled/default

# Enable the new site configuration
sudo ln -sf /etc/nginx/sites-available/custom_conf /etc/nginx/sites-enabled/


# new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}"

# sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/custom_conf

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
