#!/usr/bin/env bash
# This script configure a brand new ubuntu server and adds response header

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# configure firewall to allow request through port 80
# sudo ufw allow 'Nginx HTTP'

# Allow HTTP traffic
sudo ufw allow 80/tcp

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# Creating an index.html page
echo '
    <html>
    <head></head>
    <body>
        <h1>Hello! Welcome</h1>
        <h2>I am <strong>Ezechiel Kiregha</strong>,<br>
        Co-Founder and CEO at <strong>Kiregha Corporation.</strong></h2>
    </body>
    </html>
    ' | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
# new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ezechielkiregha permanent;"
# sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/custom_conf
sudo chmod 777 /etc/nginx/sites-available/custom_conf
# Creating a 404 Custom error page
echo "
    <html>
    <head></head>
    <body>
        <h1>CE CI N'EST PAS UNE PAGE</h1>
    </body>
    </html>
    " | sudo tee /var/www/html/404.html

sudo cat << EOF > /etc/nginx/sites-available/custom_conf
server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /redirect_me {
        return 301 https://youtube.com/@AI_Mirror_Company;
    }

    error_page 404 /404.html;

    location /404.html {
        root /var/www/html;
        internal;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}
EOF

# Delete/Desactivate the default page from enabled sites
sudo rm /etc/nginx/sites-enabled/default

# Enable the new site configuration
sudo ln -sf /etc/nginx/sites-available/custom_conf /etc/nginx/sites-enabled/

# new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

# sudo sed -i "s/error_page 404 /404.html;/$new_string/g" /etc/nginx/sites-enabled/custom_conf

# Create backup of custom Nginx configuration
sudo cp /etc/nginx/sites-available/custom_conf /etc/nginx/sites-available/custom_conf.bak

# Add X-Served-By header to Nginx configuration
sudo sed -i '/server_name _;/a \ \tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/custom_conf

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
