#!/usr/bin/env bash
# This script configure a brand new ubuntu server and adds response header

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# configure firewall to allow request through port 80
# sudo ufw allow 'Nginx HTTP'

# Allow HTTP traffic
sudo ufw allow 80/tcp

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# Creating an index.html page
echo '
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to nginx!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
    <a href="http://nginx.org/">nginx.org</a>.<br/>
    Commercial support is available at
    <a href="http://nginx.com/">nginx.com</a>.</p>

    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>
    ' | sudo tee /var/www/html/index.html

# How I solved it: delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. You do that by creating a symbolic link. 
# NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
