#!/usr/bin/env bash
# This script installs Nginx, starts it, and sets it up to listen on port 80
sudo apt-get install -y nginx
echo '<html><head></head><body><h1>Welcome to Nginx!</h1></body></html>' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx stop
