#!/usr/bin/env bash
# Bash script displays all active IPv4s on machine

#ip addr show | grep -oP 'inet \K[\d.]+'

ip_addresses=$(hostname -I)

# Display all active IPv4 IPs
echo "$ip_addresses" | grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b'
