#!/bin/bash

if ! command -v apache2 &> /dev/null
then
	echo "Installing Apache2..."
	sudo apt-get update
	sudo apt-get install apache2 -y
	echo "Apache2 installed."
else
	echo "Restarting Apache2..."
	sudo service apache2 restart
	echo "Apache2 restarted."
fi

