#!/usr/bin/env bash
# SSH client configuration

Host *
   PasswordAuthentication no
   Identifyfile ~/.ssh/school
   SendEnv LANG LC_*
   HashKnownHosts yes
   GSSAPIAuthentication yes
   GSSAPIDelegateCredentials no
